# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-12 00:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='SignOff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signoffType', models.CharField(choices=[('SHOP_HEAD', 'Shop Head'), ('SOLO', 'Solo Use'), ('SUPERVISED', 'Supervised Use'), ('NONE', 'Not Approved to use')], default='NONE', max_length=15)),
                ('signoffDate', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='machine',
            name='macAddress',
            field=models.CharField(blank=True, max_length=15, unique=True),
        ),
        migrations.AddField(
            model_name='membership',
            name='reservations',
            field=models.ManyToManyField(through='frontend.Reservation', to='frontend.Machine'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='machine',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='frontend.Machine'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='reservationEnd',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reservation',
            name='reservationStart',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='reservation',
            name='member',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='frontend.Membership'),
        ),
        migrations.AddField(
            model_name='signoff',
            name='machine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frontend.Machine'),
        ),
        migrations.AddField(
            model_name='signoff',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frontend.Membership'),
        ),
        migrations.AddField(
            model_name='signoff',
            name='signOffBy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='SignOff', to='frontend.Membership'),
        ),
        migrations.AddField(
            model_name='machine',
            name='shop',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='frontend.Shop'),
        ),
        migrations.AddField(
            model_name='membership',
            name='signoffs',
            field=models.ManyToManyField(related_name='SignOffs', through='frontend.SignOff', to='frontend.Machine'),
        ),
    ]
