# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-12 00:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0003_machine_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='reservationEnd',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='reservationStart',
            field=models.DateTimeField(null=True),
        ),
    ]
